//defines.h
#define READBIT(WORD,BIT) ((WORD>>BIT)&1)
#define WRITEBIT(WORD,BITPOS,BIT)  (WORD=(WORD&~(1<<BITPOS))|(BIT<<BITPOS))
#define READBYTE(WORD,BITSTARTPOS) ((WORD<<BITSTARTPOS)&255)
#define WRITEBYTE(WORD,BITSTARTPOS,VAL)  WORD=((WORD&~(255<<BITSTARTPOS)) | (VAL<<BITSTARTPOS))
#define READNIBBLE(WORD,BITSTARTPOS) ((WORD>>BITSTARTPOS)&15)
#define WRITENIBBLE(WORD,BITSTARTPOS,VAL) WORD=((WORD&~(15<<BITSTARTPOS))|(VAL<<BITSTARTPOS))
